version: "3.8"

services:
  backend:
    build: ./Backend
    ports:
      - "8480:5000"
    networks:
      - app-network

  frontend:
    build: ./Frontend
    ports:
      - "8400:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
